CREATE TABLE TB_BOOKING
(
    BOOKING_CODE INT NOT NULL AUTO_INCREMENT,
    RESOURCE_CODE INT NOT NULL,
    USER_CODE INT NOT NULL,
    BEGIN_HR DATETIME NOT NULL,
    END_HR DATETIME NOT NULL,
    STATUS_CODE INT NOT NULL DEFAULT 1,
    PRIMARY KEY(BOOKING_CODE)
);
