INSERT INTO TB_USER(USER_NM) VALUES('LUCIANO');
INSERT INTO TB_USER(USER_NM) VALUES('GISELE');
INSERT INTO TB_USER(USER_NM) VALUES('PIETRA');
INSERT INTO TB_USER(USER_NM) VALUES('HELENA');

INSERT INTO TB_RESOURCE(RESOURCE_NM) VALUES('incrível hulk');
INSERT INTO TB_RESOURCE(RESOURCE_NM) VALUES('thor');
