-- Create a new database called 'bookingDB'
-- Connect to the 'master' database to run this snippet
CREATE SCHEMA bookingDB;

CREATE TABLE  TB_BOOKING
(
    BOOKING_CODE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    RESOURCE_CODE INT NOT NULL,
    USER_CODE INT NOT NULL,
    BEGIN_HR DATETIME NOT NULL,
    END_HR DATETIME NOT NULL,
    STATUS_CODE INT NOT NULL DEFAULT 1
);


CREATE TABLE TB_RESOURCE
(
    RESOURCE_CODE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    RESOURCE_NM VARCHAR(300) NOT NULL
);

CREATE TABLE TB_USER
(
    USER_CODE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    USER_NM VARCHAR(300) NOT NULL
);


ALTER TABLE TB_BOOKING
ADD CONSTRAINT FK_RESOURCE_CODE FOREIGN KEY(RESOURCE_CODE) REFERENCES TB_RESOURCE;


ALTER TABLE TB_BOOKING
ADD CONSTRAINT FK_USER_CODE FOREIGN KEY(USER_CODE) REFERENCES TB_USER;

ALTER TABLE TB_BOOKING
ADD CONSTRAINT CK_STATUS_CODE CHECK(STATUS_CODE IN (1, 2, 3)) -- 1 = ATIVO, 2 = CONCLUIDO, 3 = CANCELADO
